### ISSUE TITLE
Possible Bug - Two Weight Updates for the class LinearPolicy

### ISSUE THREAD

**Issue by ghost** [jparkerholder/ASEBO#1]
In the lines **106-108** of the file [policies.py](https://github.com/jparkerholder/ASEBO/blob/master/asebo/policies.py), the weights to be optimized seem to be updated two times, as presented below:

```
    def update(self, vec):
        
        self.params += vec
        
        self.w += vec
        self.W = self.w.reshape(self.ac_dim, self.ob_dim)
```

Note that both ```self.params``` and ```self.w``` refer to the same memory (i.e., the weights to be optimized). Anyone of these two updates should be deleted, in order to ensure that the weights are updated **only once**.

**Comment by jparkerholder** [comment]
Hi - thank you for pointing this out!

You are right. The w and params were implemented for the Toeplitz policy first and then this was not properly thought through for the linear case.

I think it can be easily fixed by just using copy(). Having said that, this bug is fairly inconsequential, since all it will do is double the learning rate.
