### ISSUE TITLE
DO NOT Use the Same Environment Seed for All Train and Test Samples

### ISSUE THREAD

**Issue by ghost** [jparkerholder/ASEBO#2]
Although both the function ```do_rollouts``` and ```rollout``` provide the argument ```seed``` to set the environment seed, all their actual calls (e.g., ```w.do_rollouts()```) do not set it (and only the default value 0 is used). It causes all samples to use the same environment seed ```seed=0```, which means that the environment noise is not set properly. For different samples, different environment seeds should be used in order to test the effect of environment noise on the algorithm performance.

More importantly, the train and test case also use the same environment seed (i.e., by default ```seed=0```), since both of them do NOT set this argument. It may have a risk to over-fit for the same environment seed.

Luckily, This issue should be fixed easily.

@jparkerholder

**Comment by jparkerholder** [comment]
Hi,

Thank you for your comment and interest in the code!

This is actually a design choice - to make the environments slightly easier. All baselines used this same setting, so the results are fair. From our experiments we noted that we need more samples to train with a varying seed, and due to limited resources we wanted to focus on comparing more methods on more environments. 

I agree with you that generalization is important and interesting (in fact, it is the topic of my current work) but it was not the focus of this project, which was solely about sample efficient optimization.

Let me know if you have more questions, and Happy New Year!

Cheers
